import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      strategies: 'generateSW',
      registerType: 'autoUpdate',
      injectRegister: 'auto',
      pwaAssets: {
        disabled: false,
        preset: 'minimal',
        images: ['/logo.svg'],
      },
      manifest: {
        name: 'Salati App',
        short_name: 'Salati',
        description: 'An integrated e-commerce platform for Salati',
        theme_color: '#a9ae8b',
        icons: [
          {
            src: 'pwa-192x192.png',
            sizes: '192x192',
            type: 'image/png',
          },
          {
            src: 'pwa-512x512.png',
            sizes: '512x512',
            type: 'image/png',
          },
          {
            src: 'apple-touch-icon.png',
            sizes: '180x180',
            type: 'image/png',
            purpose: 'any',
          },
          {
            src: 'pwa-512x512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html,ico,png,svg,webmanifest}'],
        navigateFallback: 'index.html',
        navigateFallbackDenylist: [/^\/admin/],
      },
      devOptions: {
        enabled: true,
        type: 'module',
      },
      includeAssets: [
        // These are now generated by the pwaAssets plugin.
        // Removed to avoid conflict.
      ],
    }),
  ],

  server: {
    allowedHosts: ['devserver-main--salati-e.netlify.app'],
  },

  build: {
    rollupOptions: {
      input: {
        main: './index.html',
        admin: './admin.html',
      },
    },
  },
})
